import streamlit as st
import torch
from PIL import Image as PILImage
from transformers import AutoImageProcessor, SiglipForImageClassification

st.set_page_config(page_title="AI vs Human Image Detector", page_icon="🤖")

st.markdown("# AI vs Human Image Detector 🤖")
st.write(
    "Upload an image to detect if it is generated by AI or is of a real human."
)

st.write("---")

MODEL_IDENTIFIER = r"Ateeqq/ai-vs-human-image-detector"

@st.cache_resource
def load_model_and_processor():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    processor = AutoImageProcessor.from_pretrained(MODEL_IDENTIFIER)
    model = SiglipForImageClassification.from_pretrained(MODEL_IDENTIFIER)
    model.to(device)
    model.eval()
    return processor, model, device

if st.session_state.get("authentication_status"):
    try:
        with st.spinner("Loading model... this may take a moment."):
            processor, model, device = load_model_and_processor()
    except Exception as e:
        st.error(f"Error loading model: {e}")
        st.stop()

    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

    if uploaded_file is not None:
        try:
            image = PILImage.open(uploaded_file).convert("RGB")
            st.image(image, caption='Uploaded Image', use_column_width=True)
            
            st.write("Analyzing image...")
            
            with st.spinner("Running inference..."):
                inputs = processor(images=image, return_tensors="pt").to(device)
                
                with torch.no_grad():
                    outputs = model(**inputs)
                    logits = outputs.logits
                    
                predicted_class_idx = logits.argmax(-1).item()
                predicted_label = model.config.id2label[predicted_class_idx]
                
                probabilities = torch.softmax(logits, dim=-1)
                predicted_prob = probabilities[0, predicted_class_idx].item()
                
                st.subheader("Result")
                if predicted_label.lower() == 'ai':
                    st.error(f"**Prediction:** {predicted_label.upper()}")
                else:
                    st.success(f"**Prediction:** {predicted_label.upper()}")
                    
                st.info(f"**Confidence Score:** {predicted_prob:.4f}")
                
                st.write("---")
                st.write("**Scores per class:**")
                for i, label in model.config.id2label.items():
                    st.write(f"- {label}: {probabilities[0, i].item():.4f}")
                    
        except Exception as e:
            st.error(f"Error processing image: {e}")
else:
    st.warning("Please login from the Home page first to access this feature.")
